name: sky_printing
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.1.5 <4.0.0"

dependencies:
  # Flutter SDK
  flutter:
    sdk: flutter

  # Localization
  flutter_localizations:
    sdk: flutter

  # State Management
  flutter_bloc: ^8.1.3

  # dateFormat
  intl: ^0.18.1

  # Database
  floor: ^1.4.2

  # # Make Request to API
  # retrofit: ^3.0.1

  # Hooks
  flutter_hooks: ^0.18.3

  # Functional Programming
  dartz: ^0.10.1

  # Dependency Injection
  get_it: ^7.6.4

  # Network
  dio: ^5.3.3

  # Navigation
  go_router: ^11.1.1

  # Freezed
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1

  # UI
  flutter_svg: ^2.0.8
  oktoast: ^3.3.2+1
  cached_network_image: ^3.3.0

  # Utils
  equatable: ^2.0.5

  # Firebase
  firebase_core: ^2.20.0
  firebase_analytics: ^10.6.2
  firebase_crashlytics: ^3.4.2
  firebase_performance: ^0.9.3+3

  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Screen Util (Responsive)
  flutter_screenutil: ^5.9.0
  dot_navigation_bar: ^1.0.2
  google_maps_flutter: ^2.5.0
  location: ^5.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linting
  flutter_lints: ^2.0.0

  # Code Generation
  build_runner: ^2.4.6
  json_serializable: ^6.7.1

  # State Management
  bloc_test: ^9.1.5

  # Network
  http_mock_adapter: ^0.6.0

  # Freezed
  freezed: ^2.4.5
  logger: ^2.0.2+1

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins/Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins/SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins/Bold.ttf
          weight: 700
