name: sky_printing_admin
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.1.5 <4.0.0"

dependencies:
  cached_network_image: ^3.3.0
  clipboard: ^0.1.3

  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^5.3.3
  email_validator: ^2.1.17
  equatable: ^2.0.5
  ffi: ^2.1.0
  file_picker: ^6.0.0
  fluent_ui: ^4.7.7
  flutter:
    sdk: flutter
  flutter_acrylic: ^1.1.3
  flutter_bloc: ^8.1.3
  flutter_markdown: ^0.6.18
  flutter_svg: ^2.0.9
  flutter_syntax_view:
    git:
      url: https://github.com/YehudaKremer/flutter_syntax_view.git
  freezed_annotation: ^2.4.1
  get_it: ^7.6.4
  go_router: ^11.1.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^0.13.6
  intl: ^0.18.1
  json_annotation: ^4.8.1
  oktoast: ^3.3.2+1
  pdf: ^3.10.4
  socket_io_client: ^2.0.3+1
  system_theme: ^2.3.1
  url_launcher: ^6.2.1
  url_strategy: ^0.2.0
  win32: ^5.0.9
  window_manager: ^0.3.7
  windows_printing:
    path: ../../packages/windows_printing
  windows_printing_models:
    path: ../../packages/windows_printing_models

dev_dependencies:
  bloc_test: ^9.1.5
  build_runner: ^2.4.6
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.1
  flutter_native_splash: ^2.3.5
  flutter_test:
    sdk: flutter
  freezed: ^2.4.5
  http_mock_adapter: ^0.6.0
  json_serializable: ^6.7.1
  logger: ^2.0.2+1

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins/Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins/SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins/Bold.ttf
          weight: 700
